### ISSUE TITLE
no assignment to mpd_pid 

### ISSUE THREAD

**Issue by A1phaZer0** [Shinryuu/dotfiles#1]
Hi, @Shinryuu  
I saw kill $date_pid $mpd_pid in /.config/herbstluftwm/panel.sh (line 43). But mpd_pid didn't get assigned before,should it be "volume_pid"?

Brilliant work by the way,I want to use some of your configs,thanks!

**Comment by Shinryuu** [comment]
For some reason I've totally missed this issue.. I believe I've corrected it now. Sorry for the extremely long delay! I'll close this once I've confirmed it's correct.

**Comment by Shinryuu** [comment]
I've confirmed I have __mpd_pid__ now included in my __panel.sh__ file. I'll close this issue now.
